---
- name: AAP Inventory Update
  hosts: all
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "This is a test"
    - name: Pause for 5 minutes
      ansible.builtin.pause:
        minutes: 10
