---
- name: AAP Inventory Update
  hosts: localhost
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "This is a test"
    - name: Update Inventory
      ansible.controller.host:
        name: test.jlmayorga.xyz
        description: "Test Host"
        inventory: "{{ lookup('ansible.builtin.env', 'INVENTORY_ID', default='HomeLab') }}"
        enabled: false
        state: present
